### ISSUE TITLE
Exception under load

### ISSUE THREAD

**Issue by zwayne** [mlsecproject/gglsbl-rest#24]
I'm seeing this error in my logs... i'm looping through a large list & running it against gglsbl-rest. 

`mlsecproject/gglsbl-rest:latest-----44d7af4aa467 [2019-10-02 19:30:18,529] ERROR in app: exception handling [http://yoursetforupgradealways.site/]
mlsecproject/gglsbl-rest:latest-----44d7af4aa467 Traceback (most recent call last):
mlsecproject/gglsbl-rest:latest-----44d7af4aa467   File "/home/gglsbl/app.py", line 29, in _lookup
mlsecproject/gglsbl-rest:latest-----44d7af4aa467     return sbl.lookup_url(url)
mlsecproject/gglsbl-rest:latest-----44d7af4aa467   File "/usr/lib/python2.7/site-packages/gglsbl/client.py", line 120, in lookup_url
mlsecproject/gglsbl-rest:latest-----44d7af4aa467     list_names = self._lookup_hashes(url_hashes)
mlsecproject/gglsbl-rest:latest-----44d7af4aa467   File "/usr/lib/python2.7/site-packages/gglsbl/client.py", line 166, in _lookup_hashes
mlsecproject/gglsbl-rest:latest-----44d7af4aa467     self._sync_full_hashes(matching_prefixes.keys())
mlsecproject/gglsbl-rest:latest-----44d7af4aa467   File "/usr/lib/python2.7/site-packages/gglsbl/client.py", line 107, in _sync_full_hashes
mlsecproject/gglsbl-rest:latest-----44d7af4aa467     self.storage.store_full_hash(threat_list, hash_value, cache_duration, malware_threat_type)
mlsecproject/gglsbl-rest:latest-----44d7af4aa467   File "/usr/lib/python2.7/site-packages/gglsbl/storage.py", line 198, in store_full_hash
mlsecproject/gglsbl-rest:latest-----44d7af4aa467     dbc.execute(qi, i_parameters)
mlsecproject/gglsbl-rest:latest-----44d7af4aa467 OperationalError: database is locked`

**Comment by asieira** [comment]
Yes, this seems like you're stretching the limits of what sqlite can handle: https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked .

It's important to note, though, that when the application encounters an exception it will retry a few times (as defined by the `MAX_RETRIES` environment variable), so if this is happening infrequently and you don't see any 500 responses this could be ok.

I suggest you play a bit with the number of workers (`WORKERS` environment variable), maybe reducing them to ensure you are not hitting sqlite's limits. The other thing you could do is increase the number of retries (`MAX_RETRIES` environment variable) to ensure that requests are honored even when those errors occur, even if it takes a while longer.

The best bet, though, would be to run multiple ggsbl-rest containers and perform load-balancing of requests among them. Each will keep its own local sqlite database and increase your overall tolerance of concurrent requests.

Hope this helps, and sorry for the delay in responding.

I'm curious to find out if the
