### ISSUE TITLE
wrote python lib && ACE Ecosystem is using gglsbl-rest

### ISSUE THREAD

**Issue by seanmcfeely** [mlsecproject/gglsbl-rest#25]
Hi, love the project. I integrated it into some of our tools and wrote the following for interacting with it programmatically and from the cli.
https://github.com/seanmcfeely/gglsbl-rest-client

Also, I'm using your service with the above python lib as an analysis module here -> https://github.com/ace-ecosystem/ACE/blob/d49fc92dd715b96a9b760b740e3d6c7a74740b97/lib/saq/modules/url.py#L61

**Comment by asieira** [comment]
Glad to hear that, Sean! Thank you for sharing.

I'm adding both of those references to the README and also releasing a new version with updated dependencies later today.
