### ISSUE TITLE
wrong order of params in docker command in README.md

### ISSUE THREAD

**Issue by randysch** [mlsecproject/gglsbl-rest#7]
When running the docker command as given in the README,

docker run -e GSB_API_KEY=<your API key> mlsecproject/gglsbl-rest -p 127.0.0.1:5000:5000 -i

I got "connection refused" when trying to hit the service. Starting with this command worked properly:

docker run -e GSB_API_KEY=<your API key> -p 127.0.0.1:5000:5000 -i mlsecproject/gglsbl-rest 

Running Ubuntu 16.04 with Docker 17.09.0-ce

**Comment by asieira** [comment]
Updated the README as suggested, thanks for reporting this!
